version: '3'
services:
  next:
    build: .
    container_name: next
    working_dir: /app
    restart: unless-stopped
    volumes:
      - .:/app
    command: >
      sh -c "yarn build && yarn start"
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
